version: "3.8"

services:
  logging-demo:
    build: .
    ports:
      - 8081:8080
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/postgres
      - DB_USER=postgres
      - DB_PASS=elephant
    container_name: logging-container
    depends_on:
      - postgres
    volumes:
      - ../logs/application.log:/logs/application.log
      # IF THE FILE DOES NOT ALREADY EXIST, A FOLDER OF THAT NAME MIGHT BE CREATED

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=elephant
    container_name: postgres-container
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local